image: node:10.15.1

pipelines:
  branches:
    production:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - mkdir build
          - npm install --no-optional
          - npm audit fix -y
          - CI=false npm run build --silent
          - echo "Building Shade Flow Complete!"
        artifacts:
          - build/**
    - step:
        name: Deploy
        script:
          - pipe: atlassian/aws-s3-deploy:0.3.2
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
              AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
              S3_BUCKET: $S3_BUCKET
              LOCAL_PATH: 'build'
